### ISSUE TITLE
pickles data files

### ISSUE THREAD

**Issue by rmojgani** [pvlachas/RNN-Lyapunov-Spectrum#3]
Wondering if could you upload the trained data files.
I specifically encounter missing pickle files running  ``bash 0_TRAIN_RNN.sh''

`
## CONFIG: RUNNING IN LOCAL REPOSITORY.
PROJECT PATH=/**************************/RNN-Lyapunov-Spectrum
PLOTTING HOSTNAME: **************-laptop
CLUSTER=False, CLUSTER_NAME=local
-V- Matplotlib Version = 3.1.2
rnn
-V- Python Version = 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
-V- Torch Version = 1.6.0
Reference train time 23:30:00
## Model name: 
ARNN-N_used_20000-N_100000-scaler_Standard-NL_1-LR_0.001-L2_0.0-C_gru-RNN_1x40-SL_30
[ModuleList(
  (0): GRUCell(3, 40)
), ModuleList(
  (0): Linear(in_features=40, out_features=3, bias=True)
)]
# Trainable params 5523/5523
INITIALIZING PARAMETERS...

weight_ih
weight_hh
bias_ih
bias_hh
weight
bias
PARAMETERS INITIALISED!
CUDA Device available? False
Number of devices: 0
Using device: cpu
Loading Data...
Datafile
 /**************************/RNN-Lyapunov-Spectrum/Data/Lorenz3D/Data/training_data_N100000.pickle
NOT FOUND.
Traceback (most recent call last):
  File "./Models/Utils/data_utils.py", line 45, in loadDataPickle
    with open(data_path, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/*************/RNN-Lyapunov-Spectrum/Data/Lorenz3D/Data/training_data_N100000.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RUN.py", line 102, in <module>
    main()
  File "RUN.py", line 99, in main
    runModel(args_dict)
  File "RUN.py", line 27, in runModel
    trainModel(params_dict)
  File "RUN.py", line 54, in trainModel
    model.train()
  File "./Models/rnn/rnn.py", line 502, in train
    input_sequence = self.getTrainingData()
  File "./Models/rnn/rnn.py", line 470, in getTrainingData
    data = loadData(self.train_data_path, "pickle")
  File "./Models/Utils/data_utils.py", line 28, in loadData
    return loadDataPickle(data_path)
  File "./Models/Utils/data_utils.py", line 49, in loadDataPickle
    raise ValueError(inst)
ValueError: [Errno 2] No such file or directory: '*********************/RNN-Lyapunov-Spectrum/Data/Lorenz3D/Data/training_data_N100000.pickle'

`

**Comment by pvlachas** [comment]
The datafiles are now uploaded.
